PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <http://schema.org/>
PREFIX spin: <http://spinrdf.org/spin#>

CONSTRUCT {
  [] a spin:ConstraintViolation ;
    rdfs:label "At least 1 instance of schema:JobPosting must be present in the document"@en , 
      "V dokumentu musí být alespoň 1 instance schema:JobPosting"@cs
    .
} WHERE {
  FILTER NOT EXISTS {
    [] a schema:JobPosting .
  }
}
